Fix Error C2572: redefinition of default parameter
Remove reference white default definition from cpp file (since it is already declared in the header file)